-- =============================================================================
-- TalktoPlacement / CareerPlatform — PRODUCTION schema for Supabase (PostgreSQL)
--
-- SINGLE SOURCE OF TRUTH for the database schema. This file is hand-maintained:
-- there are intentionally NO EF Core migration files in the project, and the API
-- never calls Database.MigrateAsync(). To add or change a column/table/index,
-- edit THIS file and re-apply it.
--
-- Run:  Supabase SQL Editor -> paste -> Run   |   psql "$DB_URL" -f schema.sql
--
-- Idempotency: every statement is natively re-runnable
-- (CREATE TABLE/INDEX IF NOT EXISTS, ADD COLUMN IF NOT EXISTS), so applying the
-- file repeatedly is a no-op and newly-added statements are picked up on the next
-- run. Do NOT reintroduce a migration-history gate — it would silently skip new
-- statements on databases that already recorded the migration id.
--
-- The whole file runs in one transaction: either the entire schema applies or
-- nothing does.
--
-- The .NET API connects as table owner (postgres) and BYPASSES the RLS below,
-- which only locks down Supabase's auto PostgREST/anon data API.
-- =============================================================================

START TRANSACTION;


CREATE TABLE IF NOT EXISTS "AdminMeetings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "MeetingType" character varying(64) NOT NULL,
    "MentorName" character varying(200),
    "MentorCompany" character varying(200),
    "StudentName" character varying(200),
    "StudentEmail" character varying(200),
    "CohortTarget" character varying(32),
    "TargetAudienceLabel" character varying(200),
    "AttendeeCount" integer NOT NULL,
    "ScheduledAtUtc" timestamp with time zone NOT NULL,
    "DurationMinutes" integer NOT NULL,
    "Status" character varying(32) NOT NULL,
    "MeetUrl" character varying(500) NOT NULL,
    "Notes" character varying(2000),
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_AdminMeetings" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Assessments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Slug" character varying(160) NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(4000) NOT NULL,
    "Category" character varying(64) NOT NULL,
    "DurationMinutes" integer NOT NULL,
    "TotalMarks" integer NOT NULL,
    "PassingMarks" integer NOT NULL,
    "QuestionsCount" integer NOT NULL,
    "StartsAtUtc" timestamp with time zone,
    "EndsAtUtc" timestamp with time zone,
    "QuestionsJson" text NOT NULL,
    "IsPublished" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_Assessments" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Broadcasts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BroadcastType" integer NOT NULL,
    "Heading" character varying(200) NOT NULL,
    "TargetPlan" character varying(64) NOT NULL,
    "QuestionText" character varying(2000),
    "QuestionLink" character varying(500),
    "Message" character varying(4000) NOT NULL,
    "RecipientCount" integer NOT NULL,
    "SentAtUtc" timestamp with time zone NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_Broadcasts" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "CourseContents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Category" text NOT NULL,
    "FileUrl" text NOT NULL,
    "IsPaid" boolean NOT NULL,
    "IsPublished" boolean NOT NULL,
    "Price" numeric NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CourseContents" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Courses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Slug" text NOT NULL,
    "Description" text NOT NULL,
    "Price" numeric NOT NULL,
    "IsPublished" boolean NOT NULL,
    "MediaUrl" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Courses" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Enrollments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ProductType" text NOT NULL,
    "ProductId" integer NOT NULL,
    "OrderId" integer NOT NULL,
    "GrantedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Enrollments" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "InterviewQuestions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Slug" character varying(160) NOT NULL,
    "Prompt" character varying(300) NOT NULL,
    "ExpectedAnswer" character varying(8000) NOT NULL,
    "Topic" character varying(64) NOT NULL,
    "Difficulty" character varying(16) NOT NULL,
    "CompanyTags" character varying(500) NOT NULL,
    "IsPublished" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_InterviewQuestions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Languages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Slug" text NOT NULL,
    "Description" text NOT NULL,
    "IsPublished" boolean NOT NULL,
    "Price" numeric NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Languages" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "LearningPaths" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Slug" character varying(160) NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(4000) NOT NULL,
    "TargetRole" character varying(120) NOT NULL,
    "EstimatedMonths" integer NOT NULL,
    "MilestonesJson" text NOT NULL,
    "IsPopular" boolean NOT NULL,
    "IsPublished" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_LearningPaths" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Mentors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "Company" character varying(100) NOT NULL,
    "Role" character varying(100) NOT NULL,
    "YearsOfExperience" text NOT NULL,
    "Bio" text NOT NULL,
    "AvatarUrl" text NOT NULL,
    "Expertise" text NOT NULL,
    "PricePerSession" numeric NOT NULL,
    "IsActive" boolean NOT NULL,
    "VerificationStatus" character varying(20) NOT NULL,
    "Rating" numeric NOT NULL,
    "TotalReviews" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Mentors" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "MockInterviewSessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Type" character varying(32) NOT NULL,
    "Topic" character varying(64) NOT NULL,
    "DurationMinutes" integer NOT NULL,
    "Score" integer,
    "Status" character varying(32) NOT NULL,
    "RubricReportJson" text NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_MockInterviewSessions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Type" character varying(60) NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Body" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "IsDismissed" boolean NOT NULL,
    "ActionUrl" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ProductType" text NOT NULL,
    "ProductId" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "RazorpayOrderId" text NOT NULL,
    "RazorpayPaymentId" text,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "PendingRegistrations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(320) NOT NULL,
    "FullName" character varying(200) NOT NULL,
    "MobileNumber" character varying(32) NOT NULL,
    "YearsOfExperience" character varying(120),
    "IntendedRole" character varying(32) NOT NULL,
    "PasswordHash" text NOT NULL,
    "OtpHash" character varying(128) NOT NULL,
    "OtpExpiresAt" timestamp with time zone NOT NULL,
    "OtpAttemptsRemaining" integer NOT NULL,
    "OtpLastSentAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PendingRegistrations" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "PlacementCompanies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Slug" character varying(160) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Logo" character varying(500) NOT NULL,
    "Tier" character varying(64) NOT NULL,
    "CtcRange" character varying(64) NOT NULL,
    "HiringRoles" character varying(500) NOT NULL,
    "OpenPositions" integer NOT NULL,
    "Description" character varying(4000) NOT NULL,
    "IsPublished" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_PlacementCompanies" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Plans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Price" numeric NOT NULL,
    "Interval" text NOT NULL,
    "IsPublished" boolean NOT NULL,
    "Entitlements" text[] NOT NULL,
    CONSTRAINT "PK_Plans" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "PlatformSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" character varying(128) NOT NULL,
    "Category" character varying(64) NOT NULL,
    "Label" character varying(200) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "ValueType" integer NOT NULL,
    "Value" character varying(2000) NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_PlatformSettings" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "PracticeQuestions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Slug" character varying(160) NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(8000) NOT NULL,
    "Difficulty" character varying(16) NOT NULL,
    "Category" character varying(64) NOT NULL,
    "AcceptanceRate" integer NOT NULL,
    "CompanyTags" character varying(500) NOT NULL,
    "IsPublished" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_PracticeQuestions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "ResumeSubmissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Title" character varying(200) NOT NULL,
    "TemplateCode" character varying(64) NOT NULL,
    "StorageKey" character varying(500) NOT NULL,
    "AtsScore" integer,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_ResumeSubmissions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "ResumeTemplates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(64) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "PreviewUrl" character varying(500) NOT NULL,
    "IsPublished" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_ResumeTemplates" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "StudentResumeUploads" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StudentUserId" character varying(64) NOT NULL,
    "StorageKey" character varying(500) NOT NULL,
    "OriginalFileName" character varying(255) NOT NULL,
    "SizeBytes" bigint NOT NULL,
    "UploadedAtUtc" timestamp with time zone NOT NULL,
    "ExpiresAtUtc" timestamp with time zone NOT NULL,
    "AssignedMentorUserId" character varying(64),
    "AssignedAtUtc" timestamp with time zone,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_StudentResumeUploads" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "SubscriptionPlans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(64) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Currency" character varying(3) NOT NULL DEFAULT 'INR',
    "IntervalUnit" integer NOT NULL,
    "IntervalCount" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_SubscriptionPlans" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "UserProfiles" (
    "Id" text NOT NULL,
    "Email" text NOT NULL,
    "FullName" text NOT NULL,
    "PasswordHash" text,
    "PasswordResetOtpHash" character varying(128),
    "PasswordResetOtpExpiresAt" timestamp with time zone,
    "PasswordResetOtpAttemptsRemaining" integer NOT NULL,
    "PasswordResetOtpLastSentAt" timestamp with time zone,
    "Role" text NOT NULL,
    "PlanName" text NOT NULL,
    "Phone" text,
    "Designation" text,
    "Department" text,
    "YearsOfExperience" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Sections" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LanguageId" integer NOT NULL,
    "Title" text NOT NULL,
    "OrderIndex" integer NOT NULL,
    CONSTRAINT "PK_Sections" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sections_Languages_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES "Languages" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "MentorSlots" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MentorId" integer NOT NULL,
    "StartTimeUtc" timestamp with time zone NOT NULL,
    "EndTimeUtc" timestamp with time zone NOT NULL,
    "IsBooked" boolean NOT NULL,
    "MeetingLink" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MentorSlots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MentorSlots_Mentors_MentorId" FOREIGN KEY ("MentorId") REFERENCES "Mentors" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "OfferLetters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "CompanyName" text NOT NULL,
    "FileUrl" text NOT NULL,
    "Status" text NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_OfferLetters" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OfferLetters_UserProfiles_UserId" FOREIGN KEY ("UserId") REFERENCES "UserProfiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ProgressLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ContentId" integer NOT NULL,
    "WatchDurationSeconds" integer NOT NULL,
    "IsCompleted" boolean NOT NULL,
    "LogDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ProgressLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProgressLogs_CourseContents_ContentId" FOREIGN KEY ("ContentId") REFERENCES "CourseContents" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProgressLogs_UserProfiles_UserId" FOREIGN KEY ("UserId") REFERENCES "UserProfiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Transactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Amount" numeric NOT NULL,
    "PlanName" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "GatewayOrderId" text,
    "Currency" character varying(3) NOT NULL DEFAULT 'INR',
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Transactions_UserProfiles_UserId" FOREIGN KEY ("UserId") REFERENCES "UserProfiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Topics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SectionId" integer NOT NULL,
    "Title" character varying(300) NOT NULL,
    "Slug" character varying(160) NOT NULL,
    "Content" text NOT NULL,
    "OrderIndex" integer NOT NULL,
    "CompanyTags" character varying(500),
    "Frequency" character varying(32),
    "Difficulty" character varying(32),
    "ReadTimeMinutes" integer,
    "IsPaid" boolean NOT NULL DEFAULT false,
    "LastUpdatedUtc" timestamp with time zone,
    CONSTRAINT "PK_Topics" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Topics_Sections_SectionId" FOREIGN KEY ("SectionId") REFERENCES "Sections" ("Id") ON DELETE CASCADE
);
-- Premium gating for individual topics/questions (added post-launch; safe on existing DBs).
ALTER TABLE "Topics" ADD COLUMN IF NOT EXISTS "IsPaid" boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS "MeetingBookings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SlotId" integer NOT NULL,
    "StudentUserId" text NOT NULL,
    "StudentName" character varying(150) NOT NULL,
    "StudentEmail" text NOT NULL,
    "TopicNote" text NOT NULL,
    "ResumeUrl" text NOT NULL,
    "Status" character varying(50) NOT NULL,
    "MeetingUrl" text NOT NULL,
    "BookedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MeetingBookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MeetingBookings_MentorSlots_SlotId" FOREIGN KEY ("SlotId") REFERENCES "MentorSlots" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Subscriptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StudentId" text NOT NULL,
    "PlanId" integer NOT NULL,
    "TransactionId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "PricePaid" numeric(18,2) NOT NULL,
    "Currency" character varying(3) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy" text,
    CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subscriptions_SubscriptionPlans_PlanId" FOREIGN KEY ("PlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Subscriptions_Transactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Subscriptions_UserProfiles_StudentId" FOREIGN KEY ("StudentId") REFERENCES "UserProfiles" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_AdminMeetings_ScheduledAtUtc" ON "AdminMeetings" ("ScheduledAtUtc");

CREATE INDEX IF NOT EXISTS "IX_AdminMeetings_Status" ON "AdminMeetings" ("Status");

CREATE INDEX IF NOT EXISTS "IX_Assessments_Category" ON "Assessments" ("Category");

CREATE INDEX IF NOT EXISTS "IX_Assessments_IsPublished" ON "Assessments" ("IsPublished");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Assessments_Slug" ON "Assessments" ("Slug");

CREATE INDEX IF NOT EXISTS "IX_Broadcasts_BroadcastType" ON "Broadcasts" ("BroadcastType");

CREATE INDEX IF NOT EXISTS "IX_Broadcasts_SentAtUtc" ON "Broadcasts" ("SentAtUtc");

CREATE INDEX IF NOT EXISTS "IX_Courses_IsPublished" ON "Courses" ("IsPublished");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Courses_Slug" ON "Courses" ("Slug");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Enrollments_UserId_ProductType_ProductId" ON "Enrollments" ("UserId", "ProductType", "ProductId");

CREATE INDEX IF NOT EXISTS "IX_InterviewQuestions_IsPublished" ON "InterviewQuestions" ("IsPublished");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_InterviewQuestions_Slug" ON "InterviewQuestions" ("Slug");

CREATE INDEX IF NOT EXISTS "IX_InterviewQuestions_Topic" ON "InterviewQuestions" ("Topic");

CREATE INDEX IF NOT EXISTS "IX_LearningPaths_IsPublished" ON "LearningPaths" ("IsPublished");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_LearningPaths_Slug" ON "LearningPaths" ("Slug");

CREATE INDEX IF NOT EXISTS "IX_LearningPaths_TargetRole" ON "LearningPaths" ("TargetRole");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_MeetingBookings_SlotId" ON "MeetingBookings" ("SlotId");

CREATE INDEX IF NOT EXISTS "IX_MentorSlots_MentorId" ON "MentorSlots" ("MentorId");

CREATE INDEX IF NOT EXISTS "IX_MockInterviewSessions_Status" ON "MockInterviewSessions" ("Status");

CREATE INDEX IF NOT EXISTS "IX_MockInterviewSessions_UserId" ON "MockInterviewSessions" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_Notifications_UserId_IsRead" ON "Notifications" ("UserId", "IsRead");

CREATE INDEX IF NOT EXISTS "IX_OfferLetters_UserId" ON "OfferLetters" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_Orders_RazorpayOrderId" ON "Orders" ("RazorpayOrderId");

-- One Order row per gateway order id. Payment verification resolves the purchased plan and the
-- charged amount from this row, so a duplicate would make that lookup ambiguous and reintroduce the
-- plan-substitution hole this binding exists to close.
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Orders_RazorpayOrderId"
    ON "Orders" ("RazorpayOrderId");

CREATE INDEX IF NOT EXISTS "IX_Orders_UserId_Status" ON "Orders" ("UserId", "Status");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_PendingRegistrations_Email" ON "PendingRegistrations" ("Email");

CREATE INDEX IF NOT EXISTS "IX_PlacementCompanies_IsPublished" ON "PlacementCompanies" ("IsPublished");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_PlacementCompanies_Slug" ON "PlacementCompanies" ("Slug");

CREATE INDEX IF NOT EXISTS "IX_PlacementCompanies_Tier" ON "PlacementCompanies" ("Tier");

CREATE INDEX IF NOT EXISTS "IX_Plans_IsPublished" ON "Plans" ("IsPublished");

CREATE INDEX IF NOT EXISTS "IX_PlatformSettings_Category" ON "PlatformSettings" ("Category");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_PlatformSettings_Key" ON "PlatformSettings" ("Key");

CREATE INDEX IF NOT EXISTS "IX_PracticeQuestions_Category" ON "PracticeQuestions" ("Category");

CREATE INDEX IF NOT EXISTS "IX_PracticeQuestions_IsPublished" ON "PracticeQuestions" ("IsPublished");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_PracticeQuestions_Slug" ON "PracticeQuestions" ("Slug");

CREATE INDEX IF NOT EXISTS "IX_ProgressLogs_ContentId" ON "ProgressLogs" ("ContentId");

CREATE INDEX IF NOT EXISTS "IX_ProgressLogs_UserId" ON "ProgressLogs" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_ResumeSubmissions_TemplateCode" ON "ResumeSubmissions" ("TemplateCode");

CREATE INDEX IF NOT EXISTS "IX_ResumeSubmissions_UserId" ON "ResumeSubmissions" ("UserId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ResumeTemplates_Code" ON "ResumeTemplates" ("Code");

CREATE INDEX IF NOT EXISTS "IX_ResumeTemplates_IsPublished" ON "ResumeTemplates" ("IsPublished");

CREATE INDEX IF NOT EXISTS "IX_Sections_LanguageId" ON "Sections" ("LanguageId");

CREATE INDEX IF NOT EXISTS "IX_StudentResumeUploads_AssignedMentorUserId" ON "StudentResumeUploads" ("AssignedMentorUserId");

CREATE INDEX IF NOT EXISTS "IX_StudentResumeUploads_ExpiresAtUtc" ON "StudentResumeUploads" ("ExpiresAtUtc");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_StudentResumeUploads_StudentUserId" ON "StudentResumeUploads" ("StudentUserId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_SubscriptionPlans_Code" ON "SubscriptionPlans" ("Code");

CREATE INDEX IF NOT EXISTS "IX_SubscriptionPlans_IsActive" ON "SubscriptionPlans" ("IsActive");

CREATE INDEX IF NOT EXISTS "IX_Subscriptions_PlanId" ON "Subscriptions" ("PlanId");

CREATE INDEX IF NOT EXISTS "IX_Subscriptions_StudentId_Status" ON "Subscriptions" ("StudentId", "Status");

CREATE INDEX IF NOT EXISTS "IX_Subscriptions_TransactionId" ON "Subscriptions" ("TransactionId");

CREATE INDEX IF NOT EXISTS "IX_Topics_SectionId_OrderIndex" ON "Topics" ("SectionId", "OrderIndex");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Topics_SectionId_Slug" ON "Topics" ("SectionId", "Slug");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Transactions_GatewayOrderId" ON "Transactions" ("GatewayOrderId") WHERE "GatewayOrderId" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_Transactions_UserId" ON "Transactions" ("UserId");



-- =============================================================================
-- Phase 2: Certificates + Support Tickets
--
-- Additive tables applied out-of-band (no EF migration file). Idempotent — the
-- backend EF configurations under Infrastructure/Persistence/Configurations/
-- describe the same shape so the C# code still compiles and reads/writes
-- correctly. Run the DDL below once per environment via the Supabase SQL editor.
-- =============================================================================

-- Certificates — one row per issued certificate, per student.
CREATE TABLE IF NOT EXISTS "Certificates" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"                text NOT NULL,
    "Title"                 character varying(200) NOT NULL,
    "IssuedFor"             character varying(200),
    "IssuedAtUtc"           timestamp with time zone NOT NULL,
    "VerificationCode"      character varying(64) NOT NULL,
    "StorageKey"            character varying(500),
    "RevokedAtUtc"          timestamp with time zone,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Certificates" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_Certificates_UserId"
    ON "Certificates" ("UserId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Certificates_VerificationCode"
    ON "Certificates" ("VerificationCode");


-- SupportTickets — one row per student-raised ticket.
CREATE TABLE IF NOT EXISTS "SupportTickets" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"                text NOT NULL,
    "Subject"               character varying(200) NOT NULL,
    "Category"              character varying(64) NOT NULL,
    "Status"                character varying(32) NOT NULL,   -- open / pending / resolved / closed
    "Priority"              character varying(16) NOT NULL,   -- low / normal / high / urgent
    "AssignedToUserId"      text,
    "ResolvedAtUtc"         timestamp with time zone,
    "ClosedAtUtc"           timestamp with time zone,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_SupportTickets" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_SupportTickets_UserId"
    ON "SupportTickets" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_SupportTickets_Status"
    ON "SupportTickets" ("Status");


-- SupportTicketMessages — the append-only thread on each ticket.
CREATE TABLE IF NOT EXISTS "SupportTicketMessages" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TicketId"              integer NOT NULL,
    "AuthorUserId"          text NOT NULL,
    "AuthorRole"            character varying(16) NOT NULL,   -- Student / Admin / Mentor
    "Body"                  text NOT NULL,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_SupportTicketMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SupportTicketMessages_SupportTickets_TicketId"
        FOREIGN KEY ("TicketId") REFERENCES "SupportTickets" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_SupportTicketMessages_TicketId"
    ON "SupportTicketMessages" ("TicketId");


-- =============================================================================
-- Phase 3: Practice Bookmarks + Assessment Attempts
-- =============================================================================

-- Per-student bookmark on a practice question. Unique (UserId, PracticeQuestionId).
CREATE TABLE IF NOT EXISTS "PracticeBookmarks" (
    "Id"                     integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"                 text NOT NULL,
    "PracticeQuestionId"     integer NOT NULL,
    "Notes"                  character varying(1000),
    "CreatedAtUtc"           timestamp with time zone NOT NULL,
    "CreatedBy"              text NOT NULL,
    "UpdatedAtUtc"           timestamp with time zone,
    "UpdatedBy"              text,
    "Version"                bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_PracticeBookmarks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PracticeBookmarks_PracticeQuestions_PracticeQuestionId"
        FOREIGN KEY ("PracticeQuestionId") REFERENCES "PracticeQuestions" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_PracticeBookmarks_UserId"
    ON "PracticeBookmarks" ("UserId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_PracticeBookmarks_User_Question"
    ON "PracticeBookmarks" ("UserId", "PracticeQuestionId");


-- One row per student attempt at an assessment. Answers are stored as JSON so the
-- assessment's question shape can evolve in code without further schema changes.
-- Score/Percentile/TimeTaken remain NULL until SubmittedAtUtc is set.
CREATE TABLE IF NOT EXISTS "AssessmentAttempts" (
    "Id"                     integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"                 text NOT NULL,
    "AssessmentId"           integer NOT NULL,
    "StartedAtUtc"           timestamp with time zone NOT NULL,
    "SubmittedAtUtc"         timestamp with time zone,
    "Score"                  integer,
    "TotalMarks"             integer NOT NULL,
    "PassingMarks"           integer NOT NULL,
    "Percentile"             numeric(5, 2),
    "TimeTakenMinutes"       integer,
    "Passed"                 boolean,
    "AnswersJson"            text NOT NULL DEFAULT '{}',
    "CreatedAtUtc"           timestamp with time zone NOT NULL,
    "CreatedBy"              text NOT NULL,
    "UpdatedAtUtc"           timestamp with time zone,
    "UpdatedBy"              text,
    "Version"                bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_AssessmentAttempts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AssessmentAttempts_Assessments_AssessmentId"
        FOREIGN KEY ("AssessmentId") REFERENCES "Assessments" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_AssessmentAttempts_UserId"
    ON "AssessmentAttempts" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AssessmentAttempts_AssessmentId"
    ON "AssessmentAttempts" ("AssessmentId");
CREATE INDEX IF NOT EXISTS "IX_AssessmentAttempts_User_Assessment"
    ON "AssessmentAttempts" ("UserId", "AssessmentId");


-- =============================================================================
-- Mentor portal additions (hand-maintained; no EF migration).
-- Idempotent: safe to run against an already-provisioned database.
--   * Mentors."UserId" links a catalog row to the authenticated mentor user
--     (JWT subject / UserProfiles.Id) so the mentor-self endpoints can resolve
--     "my" profile / slots / sessions / reviews.
--   * MentorReviews stores the student ratings shown on the mentor feedback page
--     and feeding Mentors."Rating" / "TotalReviews".
-- =============================================================================

ALTER TABLE "Mentors" ADD COLUMN IF NOT EXISTS "UserId" character varying(64);
CREATE INDEX IF NOT EXISTS "IX_Mentors_UserId" ON "Mentors" ("UserId");

CREATE TABLE IF NOT EXISTS "MentorReviews" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "MentorId"      integer NOT NULL,
    "StudentUserId" character varying(64) NOT NULL,
    "StudentName"   character varying(150) NOT NULL,
    "Rating"        integer NOT NULL,
    "Comment"       character varying(2000) NOT NULL,
    "CreatedAtUtc"  timestamp with time zone NOT NULL,
    "CreatedBy"     text NOT NULL,
    "UpdatedAtUtc"  timestamp with time zone,
    "UpdatedBy"     text,
    CONSTRAINT "PK_MentorReviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MentorReviews_Mentors_MentorId"
        FOREIGN KEY ("MentorId") REFERENCES "Mentors" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_MentorReviews_MentorId"
    ON "MentorReviews" ("MentorId");

-- Ties a review to the session it is about. Nullable so rows predating the review flow survive,
-- and UNIQUE so a student cannot rate the same session twice (the API checks first, but the
-- constraint is what actually guarantees it under a double-submit).
ALTER TABLE "MentorReviews" ADD COLUMN IF NOT EXISTS "BookingId" integer;
CREATE UNIQUE INDEX IF NOT EXISTS "UX_MentorReviews_BookingId"
    ON "MentorReviews" ("BookingId")
    WHERE "BookingId" IS NOT NULL;


-- =============================================================================
-- Phase 4: Learning Progress
--
-- Polymorphic progress rows keyed on (UserId, ResourceType, ResourceId). A single
-- table backs Course / LearningPath / Topic tracking so we can render one unified
-- "My Learning" dashboard without a per-resource-type join graph. ResourceType is
-- enforced at the API boundary; ResourceId references whichever table matches.
-- =============================================================================

CREATE TABLE IF NOT EXISTS "LearningProgress" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"                text NOT NULL,
    "ResourceType"          character varying(32) NOT NULL,    -- Course / LearningPath / Topic
    "ResourceId"            integer NOT NULL,
    "Status"                character varying(16) NOT NULL,    -- not-started / in-progress / completed
    "PercentComplete"       integer NOT NULL DEFAULT 0,        -- 0..100
    "LastAccessedAtUtc"     timestamp with time zone NOT NULL,
    "CompletedAtUtc"        timestamp with time zone,
    "Notes"                 character varying(2000),
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_LearningProgress" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_LearningProgress_UserId"
    ON "LearningProgress" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_LearningProgress_ResourceType"
    ON "LearningProgress" ("ResourceType");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_LearningProgress_User_Resource"
    ON "LearningProgress" ("UserId", "ResourceType", "ResourceId");


-- =============================================================================
-- Phase 5: Admin-surface backfill (17 tables)
--
-- These tables back the admin/student pages that used to render hardcoded
-- `const XYZ = [...]` arrays. Each table follows the standard AuditableEntity
-- shape (CreatedAtUtc/By, UpdatedAtUtc/By, Version). Only 4 of the 17 features
-- have controllers wired in this pass — the rest have schema-only landings so
-- future turns can add controllers without a migration step.
-- =============================================================================

-- 1. Coupons -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Coupons" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code"                  character varying(64) NOT NULL,
    "Description"           character varying(500),
    "DiscountType"          character varying(16) NOT NULL,        -- 'percent' | 'flat'
    "DiscountValue"         numeric(12,2) NOT NULL,                -- percent (0-100) or INR
    "MaxRedemptions"        integer,                               -- NULL = unlimited
    "RedeemedCount"         integer NOT NULL DEFAULT 0,
    "StartsAtUtc"           timestamp with time zone,
    "ExpiresAtUtc"          timestamp with time zone,
    "IsActive"              boolean NOT NULL DEFAULT true,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Coupons" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Coupons_Code" ON "Coupons" ("Code");
CREATE INDEX IF NOT EXISTS "IX_Coupons_IsActive" ON "Coupons" ("IsActive");

-- 2. CourseReviews -----------------------------------------------------------
-- Student reviews on courses. Admin moderates via Pending → Approved | Rejected.
CREATE TABLE IF NOT EXISTS "CourseReviews" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"                text NOT NULL,
    "CourseId"              integer NOT NULL,
    "Rating"                integer NOT NULL,                      -- 1..5
    "Comment"               character varying(2000) NOT NULL,
    "Status"                character varying(16) NOT NULL DEFAULT 'pending', -- pending | approved | rejected
    "ModeratedBy"           text,
    "ModeratedAtUtc"        timestamp with time zone,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_CourseReviews" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_CourseReviews_Status" ON "CourseReviews" ("Status");
CREATE INDEX IF NOT EXISTS "IX_CourseReviews_CourseId" ON "CourseReviews" ("CourseId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_CourseReviews_UserId_CourseId"
    ON "CourseReviews" ("UserId", "CourseId");

-- 3. CmsFaqs -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "CmsFaqs" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Question"              character varying(500) NOT NULL,
    "Answer"                character varying(4000) NOT NULL,
    "DisplayOrder"          integer NOT NULL DEFAULT 0,
    "IsPublished"           boolean NOT NULL DEFAULT true,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_CmsFaqs" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_CmsFaqs_IsPublished_DisplayOrder"
    ON "CmsFaqs" ("IsPublished", "DisplayOrder");

-- 4. UserSkills --------------------------------------------------------------
-- Per-user skill matrix. One row per (user, skill).
CREATE TABLE IF NOT EXISTS "UserSkills" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"                text NOT NULL,
    "SkillName"             character varying(100) NOT NULL,
    "Category"              character varying(64) NOT NULL,
    "ProficiencyLevel"      character varying(16) NOT NULL,        -- Beginner | Intermediate | Advanced | Expert
    "DisplayOrder"          integer NOT NULL DEFAULT 0,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_UserSkills" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserSkills_UserId_SkillName"
    ON "UserSkills" ("UserId", "SkillName");
CREATE INDEX IF NOT EXISTS "IX_UserSkills_UserId" ON "UserSkills" ("UserId");

-- 5. CourseCategories --------------------------------------------------------
CREATE TABLE IF NOT EXISTS "CourseCategories" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Slug"                  character varying(64) NOT NULL,
    "Name"                  character varying(128) NOT NULL,
    "Description"           character varying(500),
    "DisplayOrder"          integer NOT NULL DEFAULT 0,
    "IsPublished"           boolean NOT NULL DEFAULT true,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_CourseCategories" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_CourseCategories_Slug" ON "CourseCategories" ("Slug");

-- 6. CmsTestimonials ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS "CmsTestimonials" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "AuthorName"            character varying(128) NOT NULL,
    "AuthorRole"            character varying(200),
    "Quote"                 character varying(2000) NOT NULL,
    "AvatarUrl"             character varying(500),
    "Rating"                integer,
    "DisplayOrder"          integer NOT NULL DEFAULT 0,
    "IsPublished"           boolean NOT NULL DEFAULT true,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_CmsTestimonials" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_CmsTestimonials_IsPublished_DisplayOrder"
    ON "CmsTestimonials" ("IsPublished", "DisplayOrder");

-- 7. CmsNavigationLinks ------------------------------------------------------
CREATE TABLE IF NOT EXISTS "CmsNavigationLinks" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Label"                 character varying(64) NOT NULL,
    "Href"                  character varying(500) NOT NULL,
    "GroupName"             character varying(32) NOT NULL DEFAULT 'header', -- header | footer
    "IsExternal"            boolean NOT NULL DEFAULT false,
    "DisplayOrder"          integer NOT NULL DEFAULT 0,
    "IsPublished"           boolean NOT NULL DEFAULT true,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_CmsNavigationLinks" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_CmsNavigationLinks_GroupName_DisplayOrder"
    ON "CmsNavigationLinks" ("GroupName", "DisplayOrder");

-- 8. PlacementRoles ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS "PlacementRoles" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Slug"                  character varying(64) NOT NULL,
    "Title"                 character varying(200) NOT NULL,
    "AvgCtcRange"           character varying(64),
    "RequirementsMarkdown"  character varying(4000),
    "IsPublished"           boolean NOT NULL DEFAULT true,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_PlacementRoles" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_PlacementRoles_Slug" ON "PlacementRoles" ("Slug");

-- 9. CourseLessons -----------------------------------------------------------
-- Ordered lessons within a course (video / article / quiz).
CREATE TABLE IF NOT EXISTS "CourseLessons" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "CourseId"              integer NOT NULL,
    "Title"                 character varying(200) NOT NULL,
    "LessonType"            character varying(16) NOT NULL DEFAULT 'video', -- video | article | quiz
    "DurationSeconds"       integer,
    "ContentUrl"            character varying(1000),
    "ContentMarkdown"       character varying(8000),
    "OrderIndex"            integer NOT NULL DEFAULT 0,
    "IsPublished"           boolean NOT NULL DEFAULT true,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_CourseLessons" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_CourseLessons_CourseId_OrderIndex"
    ON "CourseLessons" ("CourseId", "OrderIndex");

-- 10. Products ---------------------------------------------------------------
-- Non-subscription SKUs (one-time add-ons, mentorship sessions).
CREATE TABLE IF NOT EXISTS "Products" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code"                  character varying(64) NOT NULL,
    "Name"                  character varying(200) NOT NULL,
    "Description"           character varying(2000),
    "ProductType"           character varying(32) NOT NULL,        -- one-time | add-on | consultation
    "Price"                 numeric(12,2) NOT NULL,
    "Currency"              character varying(8) NOT NULL DEFAULT 'INR',
    "IsActive"              boolean NOT NULL DEFAULT true,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_Code" ON "Products" ("Code");

-- 11. PracticeQuestionBanks --------------------------------------------------
-- A named grouping of practice questions (e.g. "Amazon SDE-1 top 75").
CREATE TABLE IF NOT EXISTS "PracticeQuestionBanks" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Slug"                  character varying(64) NOT NULL,
    "Name"                  character varying(200) NOT NULL,
    "Description"           character varying(1000),
    "IsPublished"           boolean NOT NULL DEFAULT true,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_PracticeQuestionBanks" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_PracticeQuestionBanks_Slug"
    ON "PracticeQuestionBanks" ("Slug");

-- Surrogate PK (project-wide Entity<TId> convention); the UNIQUE index on
-- (BankId, QuestionId) is what prevents duplicate membership.
CREATE TABLE IF NOT EXISTS "PracticeQuestionBankItems" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "BankId"                integer NOT NULL,
    "QuestionId"            integer NOT NULL,
    "OrderIndex"            integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_PracticeQuestionBankItems" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_PracticeQuestionBankItems_BankId_QuestionId"
    ON "PracticeQuestionBankItems" ("BankId", "QuestionId");
CREATE INDEX IF NOT EXISTS "IX_PracticeQuestionBankItems_BankId_OrderIndex"
    ON "PracticeQuestionBankItems" ("BankId", "OrderIndex");

-- 12. MentorAssignments ------------------------------------------------------
-- Manual mentor→student pairings within a cohort/sprint.
CREATE TABLE IF NOT EXISTS "MentorAssignments" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "StudentUserId"         text NOT NULL,
    "MentorId"              integer NOT NULL,
    "CohortName"            character varying(128),
    "AssignedAtUtc"         timestamp with time zone NOT NULL,
    "EndedAtUtc"            timestamp with time zone,
    "Notes"                 character varying(1000),
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_MentorAssignments" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_MentorAssignments_StudentUserId_Active"
    ON "MentorAssignments" ("StudentUserId")
    WHERE "EndedAtUtc" IS NULL;

-- 13. AdminAuditLogs ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AdminAuditLogs" (
    "Id"                    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ActorUserId"           text NOT NULL,
    "ActorEmail"            character varying(320),
    "Action"                character varying(64) NOT NULL,
    "TargetKind"            character varying(64),
    "TargetId"              character varying(128),
    "Metadata"              jsonb,
    "IpAddress"             character varying(64),
    "OccurredAtUtc"         timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AdminAuditLogs" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_AdminAuditLogs_OccurredAtUtc"
    ON "AdminAuditLogs" ("OccurredAtUtc" DESC);
CREATE INDEX IF NOT EXISTS "IX_AdminAuditLogs_ActorUserId"
    ON "AdminAuditLogs" ("ActorUserId");

-- 14. OrderInvoices (denormalised ledger view for the admin orders page) -----
-- Optional/redundant with Orders + Transactions but keeps the admin surface
-- decoupled from the payments schema.
CREATE TABLE IF NOT EXISTS "OrderInvoices" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrderId"               character varying(64) NOT NULL,
    "CustomerUserId"        text NOT NULL,
    "CustomerEmail"         character varying(320),
    "ItemDescription"       character varying(500) NOT NULL,
    "Amount"                numeric(12,2) NOT NULL,
    "Currency"              character varying(8) NOT NULL DEFAULT 'INR',
    "Status"                character varying(16) NOT NULL,        -- completed | pending | refunded | failed
    "PurchasedAtUtc"        timestamp with time zone NOT NULL,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_OrderInvoices" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_OrderInvoices_OrderId" ON "OrderInvoices" ("OrderId");
CREATE INDEX IF NOT EXISTS "IX_OrderInvoices_CustomerUserId"
    ON "OrderInvoices" ("CustomerUserId");

-- =============================================================================
-- 13. Posts — user-authored articles (write-an-article workflow)
-- Lifecycle: draft -> in_review -> published, with rejected bouncing back to the
-- author for edits. Any authenticated user is an author; admins review.
-- =============================================================================
CREATE TABLE IF NOT EXISTS "Posts" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "AuthorUserId"          character varying(64) NOT NULL,
    "Title"                 character varying(200) NOT NULL,
    "Slug"                  character varying(220) NOT NULL,
    "ContentMarkdown"       text NOT NULL,
    "Excerpt"               character varying(500),
    "CoverImageUrl"         character varying(500),
    "Tags"                  character varying(500),
    "Status"                character varying(16) NOT NULL DEFAULT 'draft', -- draft | in_review | published | rejected
    "WordCount"             integer NOT NULL DEFAULT 0,
    "CharCount"             integer NOT NULL DEFAULT 0,
    "SubmittedAtUtc"        timestamp with time zone,
    "PublishedAtUtc"        timestamp with time zone,
    "ReviewedAtUtc"         timestamp with time zone,
    "ReviewedByUserId"      character varying(64),
    "ReviewNote"            character varying(2000),
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Posts" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Posts_Slug" ON "Posts" ("Slug");
CREATE INDEX IF NOT EXISTS "IX_Posts_AuthorUserId" ON "Posts" ("AuthorUserId");
CREATE INDEX IF NOT EXISTS "IX_Posts_Status" ON "Posts" ("Status");


-- =============================================================================
-- Coding-assessment engine (LeetCode-style attempts)
--
-- Adds structured questions, test cases, and per-question attempt answers so that
-- scoring can happen SERVER-SIDE. The pre-existing Assessments.QuestionsJson blob
-- is left untouched for backwards compatibility, but the runner reads from these
-- tables: an opaque JSON blob cannot express hidden test cases, and a client-
-- supplied score can never be trusted.
-- =============================================================================

-- One question within an assessment. Supports multiple-choice and coding types;
-- the type-specific columns are nullable because only one family applies at a time.
CREATE TABLE IF NOT EXISTS "AssessmentQuestions" (
    "Id"                integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "AssessmentId"      integer NOT NULL,
    "OrderIndex"        integer NOT NULL DEFAULT 0,
    -- 'mcq' | 'coding'
    "QuestionType"      character varying(16) NOT NULL,
    "Title"             character varying(300) NOT NULL,
    "PromptMarkdown"    text NOT NULL DEFAULT '',
    "Marks"             integer NOT NULL DEFAULT 1,
    -- MCQ: JSON array of option strings, plus the zero-based index of the answer.
    -- CorrectOptionIndex is never projected to a student-facing response.
    "OptionsJson"       text,
    "CorrectOptionIndex" integer,
    -- Coding: the function the student must implement and per-language starter code
    -- as a JSON object keyed by language id, e.g. {"python":"def solve(...):"}.
    "FunctionName"      character varying(128),
    "StarterCodeJson"   text,
    "TimeLimitMs"       integer NOT NULL DEFAULT 5000,
    "CreatedAtUtc"      timestamp with time zone NOT NULL,
    "CreatedBy"         text NOT NULL,
    "UpdatedAtUtc"      timestamp with time zone,
    "UpdatedBy"         text,
    CONSTRAINT "PK_AssessmentQuestions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AssessmentQuestions_Assessments_AssessmentId"
        FOREIGN KEY ("AssessmentId") REFERENCES "Assessments" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_AssessmentQuestions_AssessmentId_OrderIndex"
    ON "AssessmentQuestions" ("AssessmentId", "OrderIndex");

-- Test cases for a coding question. `IsSample` rows are shown to the student and are
-- the only ones the "Run" action may execute; the rest stay hidden and are used for
-- final scoring, so a student cannot tune a solution against the full grader.
CREATE TABLE IF NOT EXISTS "AssessmentTestCases" (
    "Id"             integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "QuestionId"     integer NOT NULL,
    "OrderIndex"     integer NOT NULL DEFAULT 0,
    "Input"          text NOT NULL DEFAULT '',
    "ExpectedOutput" text NOT NULL DEFAULT '',
    "IsSample"       boolean NOT NULL DEFAULT false,
    "Weight"         integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_AssessmentTestCases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AssessmentTestCases_AssessmentQuestions_QuestionId"
        FOREIGN KEY ("QuestionId") REFERENCES "AssessmentQuestions" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_AssessmentTestCases_QuestionId_OrderIndex"
    ON "AssessmentTestCases" ("QuestionId", "OrderIndex");

-- A student's answer to one question within one attempt. Draft saves overwrite the
-- row, so a disconnect never loses work. Awarded marks are written only by the
-- server-side grader at submit time.
CREATE TABLE IF NOT EXISTS "AssessmentAttemptAnswers" (
    "Id"                  integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "AttemptId"           integer NOT NULL,
    "QuestionId"          integer NOT NULL,
    -- MCQ answer.
    "SelectedOptionIndex" integer,
    -- Coding answer.
    "Language"            character varying(32),
    "SourceCode"          text,
    -- Grading output (server-written only).
    "AwardedMarks"        integer NOT NULL DEFAULT 0,
    "IsCorrect"           boolean,
    "PassedTestCount"     integer NOT NULL DEFAULT 0,
    "TotalTestCount"      integer NOT NULL DEFAULT 0,
    "EvaluatedAtUtc"      timestamp with time zone,
    "CreatedAtUtc"        timestamp with time zone NOT NULL,
    "CreatedBy"           text NOT NULL,
    "UpdatedAtUtc"        timestamp with time zone,
    "UpdatedBy"           text,
    CONSTRAINT "PK_AssessmentAttemptAnswers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AssessmentAttemptAnswers_AssessmentAttempts_AttemptId"
        FOREIGN KEY ("AttemptId") REFERENCES "AssessmentAttempts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AssessmentAttemptAnswers_AssessmentQuestions_QuestionId"
        FOREIGN KEY ("QuestionId") REFERENCES "AssessmentQuestions" ("Id") ON DELETE CASCADE
);
-- One answer row per (attempt, question): draft saves upsert against this key.
CREATE UNIQUE INDEX IF NOT EXISTS "UX_AssessmentAttemptAnswers_Attempt_Question"
    ON "AssessmentAttemptAnswers" ("AttemptId", "QuestionId");

-- =============================================================================
-- Admin-surface backfill tables (placement plans, mentorship plans, CMS banners,
-- CMS homepage singleton, interview rubrics). All admin-managed; no seed rows.
-- =============================================================================
CREATE TABLE IF NOT EXISTS "PlacementPlans" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Slug"          character varying(160) NOT NULL,
    "Title"         character varying(200) NOT NULL,
    "Description"   character varying(4000) NOT NULL DEFAULT '',
    "DurationWeeks" integer NOT NULL DEFAULT 0,
    "Price"         numeric(12,2) NOT NULL DEFAULT 0,
    "IsPublished"   boolean NOT NULL DEFAULT true,
    "CreatedAtUtc"  timestamp with time zone NOT NULL,
    "CreatedBy"     text NOT NULL,
    "UpdatedAtUtc"  timestamp with time zone,
    "UpdatedBy"     text,
    CONSTRAINT "PK_PlacementPlans" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_PlacementPlans_Slug" ON "PlacementPlans" ("Slug");

CREATE TABLE IF NOT EXISTS "MentorshipPlans" (
    "Id"                integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Slug"              character varying(160) NOT NULL,
    "Title"             character varying(200) NOT NULL,
    "Description"       character varying(2000) NOT NULL DEFAULT '',
    "DurationMinutes"   integer NOT NULL DEFAULT 0,
    "Price"             numeric(12,2) NOT NULL DEFAULT 0,
    "CommissionPercent" numeric(5,2) NOT NULL DEFAULT 0,
    "IsPublished"       boolean NOT NULL DEFAULT true,
    "CreatedAtUtc"      timestamp with time zone NOT NULL,
    "CreatedBy"         text NOT NULL,
    "UpdatedAtUtc"      timestamp with time zone,
    "UpdatedBy"         text,
    CONSTRAINT "PK_MentorshipPlans" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_MentorshipPlans_Slug" ON "MentorshipPlans" ("Slug");

CREATE TABLE IF NOT EXISTS "CmsBanners" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title"        character varying(200) NOT NULL,
    "Message"      character varying(500) NOT NULL,
    "LinkUrl"      character varying(500),
    "Tone"         character varying(16) NOT NULL DEFAULT 'info',
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    "IsActive"     boolean NOT NULL DEFAULT true,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy"    text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy"    text,
    CONSTRAINT "PK_CmsBanners" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_CmsBanners_DisplayOrder" ON "CmsBanners" ("DisplayOrder");

CREATE TABLE IF NOT EXISTS "CmsHomepageConfigs" (
    "Id"                integer NOT NULL,
    "HeroTitle"         character varying(200) NOT NULL DEFAULT '',
    "HeroSubtitle"      character varying(500) NOT NULL DEFAULT '',
    "PrimaryCtaLabel"   character varying(64) NOT NULL DEFAULT '',
    "PrimaryCtaHref"    character varying(500) NOT NULL DEFAULT '',
    "SecondaryCtaLabel" character varying(64) NOT NULL DEFAULT '',
    "SecondaryCtaHref"  character varying(500) NOT NULL DEFAULT '',
    "CreatedAtUtc"      timestamp with time zone NOT NULL,
    "CreatedBy"         text NOT NULL,
    "UpdatedAtUtc"      timestamp with time zone,
    "UpdatedBy"         text,
    CONSTRAINT "PK_CmsHomepageConfigs" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "InterviewRubrics" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title"        character varying(200) NOT NULL,
    "Description"  character varying(2000) NOT NULL DEFAULT '',
    "Weight"       integer NOT NULL DEFAULT 0,
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    "IsPublished"  boolean NOT NULL DEFAULT true,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedBy"    text NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedBy"    text,
    CONSTRAINT "PK_InterviewRubrics" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_InterviewRubrics_DisplayOrder" ON "InterviewRubrics" ("DisplayOrder");

-- =============================================================================
-- Student self-service profile tables
--
-- These back three student pages that previously rendered hardcoded values:
--   * /student/profile/education   showed a fixed "B.Tech ... CGPA 9.2/10.0" for every student
--   * /student/profile/preferences had two toggles that mutated local state and never persisted
--   * /student/resume/[id]/edit    held the draft in a client-only store, lost on remount
--
-- Deliberately NOT added: a placement-readiness table. The readiness score is derived on read from
-- LearningProgress, AssessmentAttempts, MockInterviewSessions, UserSkills and ResumeSubmissions, so
-- it cannot drift from the underlying facts and needs no refresh job.
-- =============================================================================

-- 1. StudentEducations --------------------------------------------------------
-- One row per qualification claimed by a student, newest first in the UI. Grade is stored as a
-- (value, scale) pair rather than a bare number so a 9.2/10 CGPA and an 82/100 percentage are both
-- representable without the UI guessing which convention a row uses.
CREATE TABLE IF NOT EXISTS "StudentEducations" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"                text NOT NULL,
    "Degree"                character varying(200) NOT NULL,        -- e.g. 'B.Tech in Computer Science'
    "Institution"           character varying(200) NOT NULL,
    "FieldOfStudy"          character varying(160),
    "StartYear"             integer NOT NULL,
    "EndYear"               integer,                                -- NULL while still studying
    "IsCurrent"             boolean NOT NULL DEFAULT false,
    "GradeValue"            numeric(6,2),                           -- NULL = not disclosed
    "GradeScale"            character varying(16),                  -- 'cgpa-10' | 'cgpa-4' | 'percentage'
    "Description"           character varying(1000),
    "DisplayOrder"          integer NOT NULL DEFAULT 0,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_StudentEducations" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_StudentEducations_UserId" ON "StudentEducations" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_StudentEducations_UserId_DisplayOrder"
    ON "StudentEducations" ("UserId", "DisplayOrder");

-- 2. StudentPreferences -------------------------------------------------------
-- Exactly one row per user (enforced by the unique index). Modelled as its own table rather than
-- columns on "UserProfiles" so new switches can be added without widening the hot profile row that
-- every authenticated request reads.
CREATE TABLE IF NOT EXISTS "StudentPreferences" (
    "Id"                        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"                    text NOT NULL,
    "EmailNotificationsEnabled" boolean NOT NULL DEFAULT true,
    "RecruiterVisibility"       boolean NOT NULL DEFAULT false,     -- opt-IN: never share a profile by default
    "MentorshipRemindersEnabled" boolean NOT NULL DEFAULT true,
    "PromotionalEmailsEnabled"  boolean NOT NULL DEFAULT false,     -- opt-IN for marketing consent
    "PreferredRole"             character varying(160),
    "PreferredLocations"        character varying(500),             -- comma-separated
    "CreatedAtUtc"              timestamp with time zone NOT NULL,
    "CreatedBy"                 text NOT NULL,
    "UpdatedAtUtc"              timestamp with time zone,
    "UpdatedBy"                 text,
    "Version"                   bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_StudentPreferences" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_StudentPreferences_UserId"
    ON "StudentPreferences" ("UserId");

-- 3. ResumeDrafts -------------------------------------------------------------
-- Structured, still-editable resume content, kept separate from "ResumeSubmissions" (a finished
-- artifact submitted for review). "ContentJson" holds the builder document; the shape is owned by
-- the frontend builder and validated for size only, so adding a section does not need a migration.
CREATE TABLE IF NOT EXISTS "ResumeDrafts" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"                text NOT NULL,
    "Title"                 character varying(200) NOT NULL,
    "TemplateCode"          character varying(64) NOT NULL,
    "ContentJson"           text NOT NULL DEFAULT '{}',
    "LastEditedAtUtc"       timestamp with time zone NOT NULL,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "CreatedBy"             text NOT NULL,
    "UpdatedAtUtc"          timestamp with time zone,
    "UpdatedBy"             text,
    "Version"               bigint NOT NULL DEFAULT 0,
    CONSTRAINT "PK_ResumeDrafts" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_ResumeDrafts_UserId" ON "ResumeDrafts" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_ResumeDrafts_UserId_LastEditedAtUtc"
    ON "ResumeDrafts" ("UserId", "LastEditedAtUtc");

-- =============================================================================
-- Commit the whole schema atomically. Keep this as the LAST statement in the
-- file so any statement appended above is included in the same transaction.
-- =============================================================================
COMMIT;
